server:
  port: 9000
spring:
  application:
    name: xilixili-es
spring-es:
  es:
    hostlist: ${eshostlist:127.0.0.1:9200}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka