spring:
  application:
    name: xilixili-zuul
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
server:
  port: 9001
