server:
  port: 7777
spring:
  application:
    name: eureka-search
xilixili:
  elasticsearch:
    hostlist: ${eshostlist:127.0.0.1:9200}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka