server:
  port: 8201
spring:
  application:
    name: xilixili-userInfo
  zipkin:
    base-url: http://10.12.159.73:9000
  sleuth:
    sampler:
      probability: 1.0

  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
qiniu:
  accessKey: PvgmdZnNgC_63c27wjwAf8a4T9d8-QB2BUcd3SqZ
  secretKey: LivLDOhGnfIIE1E_YmzTo1FeBlLwjf3vi6WHGCN8
  buckName: liujundashagiao
  url: http://qd1din5hx.bkt.clouddn.com/
